### ISSUE TITLE
Typo in book - Binary write functions - fopen mode should be "wb"

### ISSUE THREAD

**Issue by Ivo-Balbaert** [dragon-language-projects/dragon-core#7]
**Describe the bug**

The code on p. 146 for writeBoolean:  

select "files"
f = fopen("text.txt","w")
writeBoolean(f,true)
flush(f)
fclose(f)

fails with a java.lang.NullPointerException:

null in main
        at writeBoolean: com.aavesh.modules.files.files$writeBoolean@2f08168

java.lang.NullPointerException
        at com.aavesh.modules.files.files$writeBoolean.execute(files.java:400)
        at com.aavesh.modules.files.files$FileFunction.execute(files.java:162)
 

**To Reproduce**
Run program in file or dragon shell

**Expected behavior**
Write to file succeeded

** Solution**
fopen mode should be "wb" instead of "w"
f = fopen("text1.txt","wb")

Same goes for functions writeByte / writeChar / writeDouble / ... writeUTF(

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Dragon 1.9.7

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ghost** [comment]
Thabm
